### ISSUE TITLE
 Metadata version mismatch for module  ArchwizardModule , found version 4, expected 3

### ISSUE THREAD

**Issue by bekijerry** [madoar/angular-archwizard#132]
hi dears
i am using angular cli version of 1.4.2 and i have installed the ArchwizardModule. At first i works fine but after i restarted my pc it shows me an error of "Metadata version mismatch for module  ArchwizardModule , found version 4, expected 3",how can i resolve this issue.please help me ASAP!

**Comment by madoar** [comment]
This error occurs, because you're using `angular-archwizard` together with angular version 4.
`angular-archwizard` version `3.0.0` is compatible with angular 5+.
If you want to use the library together with angular 4 you need to use the older `ng2-archwizard` version `2.1.0`, which you can also find on npm.
