### ISSUE TITLE
Transition to step 2 only if the api call was successful

### ISSUE THREAD

**Issue by sushmit-oodles** [madoar/angular-archwizard#135]
i am confused about the preFinalize and canEnter attributes.

My Step1 has preFinalize on it which runs a function which hits and api.
Now my Step2 has [canEnter] attribute on it which returns true or false (code take from this link: https://github.com/madoar/angular-archwizard-demo/blob/master/src/app/can-enter-event/can-enter-event.component.ts).

when my function from preFinalize runs on api success i am changing the value of variable "this.canEnterStep2Forwards" to "true" and if it fails then i set the value to "false".

Now According to this my wizard should not transition to second step if api fails but it is still going to second step when the api fails?

how do i make it transition to second step only if the api hit is successful and make it stay on step1 if api hit fails?

**Comment by madoar** [comment]
Without seeing your code for `preFinalize`, it's hard for me to help.

With the information you've written, I believe the reason is that you're using `preFinalize` to check an server API call, which you use to change an internal flag, i.e. `canEnterStep2Forwards`
This is problematic, because the server API calls normally work asynchronous, i.e. you use a `Promise` or a similar construct.
The `Promise` object executes your callback method after it receives an answer from your server.
Most likely this is after the wizard has executed the `canEnter`.

A better approach would be to use `canEnter` to execute the server API call, and to let it return a `Promise<boolean>` object.

**Comment by madoar** [comment]
If this question is still relevant/open, feel free to open a new issue.
