### ISSUE TITLE
[canExit] called too many times

### ISSUE THREAD

**Issue by adriellr01** [madoar/angular-archwizard#142]
Hello, I am using this component and I need to use [canExit] to perform some validations, but these validations are called even without any transition (when the wizard starts) and remains calling my validations forever. Please can anyone help me how to make validations only when press the button for the next step?

**Comment by madoar** [comment]
@adriellr01 what do you mean with "calling my validations forever"?
Normally the validations are only called before a step is transitioned.
Can you provide a short code snipping showcasing your issue?

**Comment by benshabatnoam** [comment]
Hi,
I'm having the same issue, I'll try to upload a sample project.
10x

**Comment by LKU4** [comment]
You probably already solved this, but maybe someone will look for solution here:

The problem is that [canExit] accepts either a boolean or a function that returns a boolean. But what you have done here is you passed a result of the function that returns a boolean, `[canExit]="canExit()"`. This means that this function is evaulated with each change detection in order to bind the up-to-date value. The correct way to do this is to pass the function itself with `[canExit]="canExit"` and the wizard will call it on his own when necessary.

**Comment by madoar** [comment]
Yes, it is as @LKU4 mentioned. When you bind the result of a method call to `[canExit]` angular will reevaluate the function with each change detection. This can be prevented by binding the function itself to `[canExit]`.

**Comment by benshabatnoam** [comment]
I understand the problem with my code, and I did what @LKU4 suggested, and he is correct. As a note I will say that I'm not sure if this was or wasn't @adriellr01 question in the first place, has he didn't reply to this further discussion...

Not sure what he meant by

> these validations are called even without any transition (when the wizard starts) and remains calling my validations forever

I guess it look like my case... although in my case the validations stopped after 4 times and didn't run *forever*

Thanks all for your help
