### ISSUE TITLE
Can we have an example or possibly code starter project?

### ISSUE THREAD

**Issue by forvy** [madoar/angular-archwizard#197]
Related to: https://github.com/madoar/angular-archwizard/issues/4 and https://github.com/madoar/angular-archwizard/tree/v1.6.0. I've tried and check to use the following: 
```
<aw-wizard-step (stepEnter)="enterStep($event)">
  <ng-template awWizardStepTitle>
    <span class="hidden-sm-down">Delivery address</span>
    <span class="hidden-md-up">Address</span>
  </ng-template>
</aw-wizard-step>
```

to make wizard title responsive, but doesn't seem to work. Did I miss something?

I'm using angular 7 and archwizard 3.0, [Stackblitz Demo](https://stackblitz.com/edit/angular-archwizard-simple-demo-edsmgs?file=src/app/app.component.html).

Does adding the following css the way?
```
@media (max-width:640px) {
  .hidden-sm-down {
    display: none;
  }

  .hidden-md-up {
    display: initial;
  }
}

@media (min-width:641px) {
  .hidden-sm-down {
    display: initial;
  }

  .hidden-md-up {
    display: none;
  }
}
```

Also, to get the current step I've tried to implement:

```
  @ViewChild(WizardComponent)
  public wizard: WizardComponent;
  getData(){
    this.wizard.wizardSteps._results.forEach(res=>{
      if(res.selected){
        console.log(res.stepTitle, res);
      }
    });
  }
```

is that the correct way? Note that there is a warning though, but it works apparently: 
![image](https://user-images.githubusercontent.com/17746819/54909430-c25c0580-4f1c-11e9-8322-86ab0910ac24.png)

Also, can we have an example of how to use in Readme.md in [Stackblitz](https://stackblitz.com/) [Project Template](https://stackblitz.com/fork/angular) like in the following: https://github.com/angular/material2?

**Comment by madoar** [comment]
The most likely reason why it is not working is because `hidden-sm-down` and `hidden-md-up` are a part of bootstrap and not `angular-archwizard`. 

About an example:
We currently provide no Stackblitz template, but if you have one or want to provide one feel free to open a PR! Instead we provide a demo repository with multiple examples. For your use-case you can find an example [here](https://madoar.github.io/angular-archwizard-demo/#/custom-step-titles). When opening the example you will see that the step title of the second step changes based on the size of your browser. The source code for the example can be found [here](https://github.com/madoar/angular-archwizard-demo/blob/develop/src/app/custom-step-titles/custom-step-titles.component.html).
