### ISSUE TITLE
Performing validation on awGoToStep

### ISSUE THREAD

**Issue by Taren-Ko** [madoar/angular-archwizard#205]
In my program, we currently have a save button and a next button, but we want to merge these into one button which saves the data on the current page before moving to the next one. I set up the Next button so that onBtnClick it performs the save functionality and validates that the user can go to the next screen, if it is not valid (doesn't save) a boolean flag is set to false. On the same button is an awGoToStep tag and on the aw-wizard-step I have canExit tied to this boolean value. Unfortunately, when I click next, awGoToStep is fired first, and then the Save/Validation function is fired. This means that the wizard does not move forward and breaks the flow. Is there any way to have this button perform it's validation function first, and THEN attempt to perform awGoToStep?

**Comment by madoar** [comment]
Is it absolutely necessary to trigger the validation by clicking on the "save and continue" button? Is it for example also ok to check the validation of the form automatically in the background whenever an input has been made or via a second button?

About the procedure of a button click using `awGoToStep`:
- first the navigation mode checks whether a step can be exited/entered via `canExit`/`canEnter`
- next the `preFinalize` event emitter of the element with the `awGoToStep` directive is called
- then the wizard transitions to the next step (calling `stepExit` event emitter of the previous step and `stepEnter` of the destination step)
- finally the `postFinalize` event emitter of the element with the `awGoToStep` directive is called

I wouldn't recommend you to assign a callback/listener to the `(click)` event emitter of the same element to which you've added `awGoToStep`, because this could conflict with the `awGoToStep` in an unexpected way.

**Comment by Taren-Ko** [comment]
For this application it was necessary to merge the save and continue functionality together. I was able to resolve this by adding a ViewChild of the Wizard to my component.ts and then after validation calling
`this.wizard.navigation.goToStep(dest);` directly in the component and removing awGoToStep in the HTML. This ensures that the exit only occurs after a successful validation and save.
