### ISSUE TITLE
Question - How to add dynamic wizard step for wizard on Click

### ISSUE THREAD

**Issue by biddingLV** [madoar/angular-archwizard#210]
Hey, sorry if I am asking something whats already here. I have more question than issue, but I want to achieve something like this, lets say, for example, I have simple wizard with 2 steps and when the user opens the first step in the wizard, he or she can click on "Add" or "Next" buttons. If the user clicks on "Add" button, I want to add a new step to wizard with pretty much the same content what's in the first step(current step). From functional side button "Add" would be lets say, Adding n+ orders without closing wizard, so it could be n+ steps, depends how many orders the user wants to create. If the user clicks on "Next" - it just proceeds with the flow. Not sure how to do achieve this, any hints, comments are welcome. Is this even possible?

ATM: I was thinking to use simple form with form array and when the user clicks on "add" I just add a new group to the Form Array, our I have n+ different forms with groups/form arrays.

Is it possible to add hidden step for this? And when the user clicks on "Add" [awGoToStep]="{stepIndex: 2} whats the hidden step"? Or maybe disable/hide naviagation bar and then just use GoToStep to kind of make/add those steps dynamically.

**Comment by madoar** [comment]
In theory you should be able to add a list of wizard steps dynamically to the wizard via `*ngFor`:

```typescript
<aw-wizard-step *ngFor="...">
   ...
</aw-wizard-step>
```

When adding wizard steps dynamically via `*ngFor` and `*ngIf` you need to watch out that you add wizard steps only **after** the current step the user is in. Otherwise you risk breaking the internal state of the wizard.

For an example how to use `*ngFor` with `angular-archwizard` also see [here](https://madoar.github.io/angular-archwizard-demo/#/wizard-step-ngfor) and [here](https://github.com/madoar/angular-archwizard-demo/tree/develop/src/app/wizard-step-ngfor)

**Comment by madoar** [comment]
You can handle the navigation part by using a `stepId` for each fixed (non-generated) wizard-step you want to be able to jump to.

**Comment by madoar** [comment]
I think the question has been satisfactorily answered? If there are any remaining questions feel free to open a new issue.
