### ISSUE TITLE
How to stop marking visited step green in Custom Navigation mode ?

### ISSUE THREAD

**Issue by AbhijitMuke** [madoar/angular-archwizard#281]
Hi, thanks for this quick demo.

I am following the custom navigation mode from this demo [https://madoar.github.io/angular-archwizard-demo/#/navigation-mode/custom](url)

But I can see the visited step is also getting marked green in the forwarding step. 

> In my application, I want to stop marking green for the visited step ( which is not completed )

I tried multiple things from - [https://github.com/madoar/angular-archwizard-demo/blob/develop/src/app/custom-navigation-mode/custom-navigation-mode.ts](url) but not in success.

A Step should not be marked green until and unless it is completed, in above demo the forwarding visited step getting marked green although it is not completed.

Please suggest  !!!

**Comment by madoar** [comment]
Currently `angular-archwizard` automatically assumes that a step has been completed when the user exits it. The biggest challenge when differentiating between exiting a step and marking at as completed and not marking it as completed is: how do you detect that the step is completed in the first place? 

`angular-archwizard` answers this question by assuming that a user is only allowed to exit a step when it has been completed. In theory one way to change this is to implement the `transition` method of your navigation mode. More specific you will need to do the following steps in your `transition` method:

1.  Fetch the current step of the wizard the user wants to leave (i.e. `wizard.currentStep`) and somehow determine whether it should be marked as completed
2.  If it should be marked as completed set `wizard.currentStep.completed = true` otherwise `wizard.currentStep.completed = false`
3.  Transition to the next step (i.e. call `super.transition(...)`)

**Comment by AbhijitMuke** [comment]
Thanks for the quickest reply.

> Yes, I am able to use transition() method override to check for visited but not completed step with the help of my business service.

Thanks a lot for writing such a wonderful flexible framework :+1:
