### ISSUE TITLE
Go to another step

### ISSUE THREAD

**Issue by ngtrdai197** [madoar/angular-archwizard#295]
Currently I'm having trouble getting to any step. In the example I have 5 steps, I can go to step 1,2,3 easily, but when I want to go to step 4,5, it is not possible. It's always in step 1. So what do I do?
```
<aw-wizard #wizard>
      <aw-wizard-step stepTitle="Title of step 1">
        Content of Step 1
      </aw-wizard-step>
      <aw-wizard-step stepTitle="Title of step 2" >
        Content of Step 2
      </aw-wizard-step>
      <aw-wizard-step stepTitle="Title of step 3">
        Content of Step 3
      </aw-wizard-step>
      <aw-wizard-step stepTitle="Title of step 4">
        Content of Step 4
      </aw-wizard-step>
      <aw-wizard-step stepTitle="Title of step 5">
        Content of Step 5
      </aw-wizard-step>
</aw-wizard>
```

```
@ViewChild('wizard', { static: false }) public wizard: WizardComponent
function (){
if (this.wizard && this.currentStep) {
      this.wizard.goToStep(this.currentStep - 1)
    }
}
```

**Comment by madoar** [comment]
Your code is missing how you navigate to the next step(s).

```typescript
function (){
if (this.wizard && this.currentStep) {
      this.wizard.goToStep(this.currentStep - 1)
    }
}
```

This is an anonymous function which navigates your wizard backwards. In addition it seems to not be used?

**Comment by ngtrdai197** [comment]
function () is just an example, in practice it would be: 
```typescript 
function gotoStep () {
    if (this.wizard && this.currentStep) {
      this.wizard.goToStep(this.currentStep - 1)
    }
}

**Comment by madoar** [comment]
Your function

```typescript
function gotoStep () {
    if (this.wizard && this.currentStep) {
      this.wizard.goToStep(this.currentStep - 1)
    }
}
```

has two issues:
- `this.currentStep` does not exist. I think you either mean `wizard.currentStep` or `wizard.currentStepIndex`
- if you mean `wizard.currentStepIndex` then it won't work because you are trying to navigate *backwards*. This won't work because you are already in the first step, which you can not leave in backwards direction

I recommend you to use the navigation directives:
- `awGoToStep`
- `awNextStep`
- `awPreviousStep`

which are explained in the [README](https://github.com/madoar/angular-archwizard#awgotostep).
In addition you can find examples on their usage in the [demo repository](https://github.com/madoar/angular-archwizard-demo).

If this functionality does not cover your requirements then you can use the API provided in the `WizardComponent`. Here I also recommend you to take a look at the [README](https://github.com/madoar/angular-archwizard#navigating-the-wizard-programmatically). Please be aware that `WizardComponent#goToStep` requires an index as its input and not a wizard step.

If you have a more concrete problem you need help with, please provide a more complete snippet which illustrates what you want to do and what blocks you.

**Comment by madoar** [comment]
If you continue to face this issue feel free to open a new issue
