### ISSUE TITLE
DEPRECATION WARNING - !global assignments

### ISSUE THREAD

**Issue by khocef** [madoar/angular-archwizard#303]
remote:        [INFO] DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
remote:        [INFO] declare new variables. Since this assignment is at the root of the stylesheet,
remote:        [INFO] the !global flag is unnecessary and can safely be removed.
remote:        [INFO]
remote:        [INFO]    ╷
remote:        [INFO] 49 │ $wz-param-indicator-state: null !global;
remote:        [INFO]    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:        [INFO]    ╵
remote:        [INFO]     node_modules/angular-archwizard/variables.scss 49:1  @import
remote:        [INFO]     node_modules/angular-archwizard/archwizard.scss 1:9  @import
remote:        [INFO]     stdin 14:9                                           root stylesheet
remote:        [INFO]
remote:        [INFO] DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
remote:        [INFO] declare new variables. Since this assignment is at the root of the stylesheet,
remote:        [INFO] the !global flag is unnecessary and can safely be removed.
remote:        [INFO]
remote:        [INFO]    ╷
remote:        [INFO] 52 │ $wz-param-indicator-color: null !global;
remote:        [INFO]    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:        [INFO]    ╵
remote:        [INFO]     node_modules/angular-archwizard/variables.scss 52:1  @import
remote:        [INFO]     node_modules/angular-archwizard/archwizard.scss 1:9  @import

**Comment by madoar** [comment]
Which version of `angular-archwizard` are you using?

**Comment by khocef** [comment]
Version 5.0.1 with Angular 8.2.14

**Comment by madoar** [comment]
This has been fixed in the version `6` releases. I thought I completely backported the fix to version `5.0.1` in #269 but it seems like I missed some changes.

I'm not sure whether I will backport the fix for the remaining variables, because of multiple reasons:
-  it is only a deprecation warning and does not break any code
-  it only affects the version `5` releases and not the current version `6` releases
-  Angular 10 has been released last month so I will release a version `7` of `angular-archwizard` soonish

Therefore I don't think that it is worth it to invest time into fixing these warning and publishing a new release.

**Comment by khocef** [comment]
okay, i will close the issue
