### ISSUE TITLE
can we create multiple instance OR nested wizard

### ISSUE THREAD

**Issue by sunilmkamble17** [madoar/angular-archwizard#305]
Is it possible to create nested wizards?
I came across requirement where I want to create nested wizard,
I am able to create HTML/view which represents design/structure of nested wizrd using following:
`<aw-wizard>
  <aw-wizard-step stepTitle="Steptitle 1">
    Step 1	
	<aw-wizard-step stepTitle="SubSteptitle 1">
		Sub Step 1
	</aw-wizard-step>
	<aw-wizard-step stepTitle="SubSteptitle 2">
		Sub Step 2
	</aw-wizard-step>
	<aw-wizard-step stepTitle="SubSteptitle 3">
		Sub Step 3
	</aw-wizard-step>
  </aw-wizard-step>
  <aw-wizard-step stepTitle="Steptitle 2">
    Step 2
  </aw-wizard-step>
  <aw-wizard-step stepTitle="Steptitle 3">
    Step 3
  </aw-wizard-step>
</aw-wizard>`

But in component.ts, I am not able to get two separate instances of the wizard
**@ViewChild(WizardComponent) public wizard: WizardComponent;
@ViewChild(WizardComponent) public subWizard: WizardComponent;

this.subWizard.navigation.goToNextStep(); //triggers next step of wizard instead of subWizard**

is it possible to create nested wizards?

![image](https://user-images.githubusercontent.com/48831944/87837167-407db180-c8b0-11ea-97f8-649439eb1ad8.png)

**Comment by madoar** [comment]
> But in component.ts, I am not able to get two separate instances of the wizard
**@ViewChild(WizardComponent) public wizard: WizardComponent;
@ViewChild(WizardComponent) public subWizard: WizardComponent;

You need to select your wizard by their id instead of their component type. Otherwise you will most likely get the same wizard in both variables.

> is it possible to create nested wizards?

I haven't tried to create nested wizards until now, therefore I can not say for sure. In theory it should be possible. The only problem you could face are that the wizard steps of your subwizard(s) are assigned to the parent wizard. You will need to test this.

It would be nice if you could give me feedback if nested wizards are working :) This would allow us to add an example for this to the demo repository.

**Comment by madoar** [comment]
An example for nested wizards has been added to the demo repository, see: [here](https://github.com/madoar/angular-archwizard-demo/tree/develop/src/app/nested-wizards) and [here](https://madoar.github.io/angular-archwizard-demo/#/nested-wizards)
