### ISSUE TITLE
Completed navigation line color is not changing after version 6 upgrade

### ISSUE THREAD

**Issue by AbhijitMuke** [madoar/angular-archwizard#314]
Hello Team, thanks for upgrading the library in order to support for Angular 9+ versions.

After upgrading to [version 6](https://github.com/madoar/angular-archwizard/releases/tag/v6.0.0) I observed the the navigation line between the icons styling keep same as it is regardless of the completion step.

Previously, it was updating the line color w.r.t state of Step color.

I guess, it is change after [:before to :after](https://github.com/madoar/angular-archwizard/pull/252) - @madoar 

**Can you help me to update the navigation line color w.r.t state of step as previously, I don't find any other way as of now there to add conditional styling for navigation line.**

**Comment by madoar** [comment]
Yes this should be because of the change from `:before` to `:after`. In theory it should be sufficient to replace the occurrences of `:before` with `:after` inside your CSS. For a simple example please look [here](https://madoar.github.io/angular-archwizard-demo/#/custom-css/line) and [here](https://github.com/madoar/angular-archwizard-demo/tree/develop/src/app/custom-line-css). If you need additional help please post a short code snippet that can be built which illustrates your issue.
