### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by Tiago-UJ** [madoar/angular-archwizard#321]
when will angular-archwizard@6.1.0 currently available for download on npm for angular 9, be update to angular-archwizard@7.0.0 for angular 10?

**Comment by madoar** [comment]
Sorry about my late reply. There are some small changes that are still missing before I will release version `7.0.0`.

**Comment by EslamElmadny** [comment]
I'm looking for version 7.0.0 too as am using angular 10

**Comment by madoar** [comment]
Today I released version `7.0.0` of `angular-archwizard` it is built using Angular 11.

Independent of the release today I think that you are misunderstanding the compatibility table.
The table does not strictly define which version of `angular-archwizard` is compatible with which version of Angular. 
It only specifies which version of `angular-archwizard` is built with which version of Angular.
Because an Angular version is normally compatible with other versions of Angular this means that a version of `angular-archwizard` can also normally be used with a previous or later version of Angular than it is built with.

To give an example:
`angular-archwizard` version `6.1.0` is not only compatible with Angular 9 (with which it is built) but also with Angular 10 and 11 :)
