### ISSUE TITLE
Not able to know the current index and total index after a step enter.

### ISSUE THREAD

**Issue by vincent-cm** [madoar/angular-archwizard#71]
If the wizard step is programmatically added, and then enter a specific step how I get which step I am in and what total step index is?

I think this feature is better to add on event emitter in (postFinalize)
considering each wizard step is programmed and determined by what value was submitted in the previous step.

**Comment by madoar** [comment]
I'm not sure what you mean by programmed?
It's currently not recommended to modify the steps at runtime, especially the steps which are already completed, because the wizard doesn't detect the changes.
I.e. if you're currently located in the third step and remove the second one, you'll be located in the previously fourth step, without having the third one completed yet.

To detect the current step index you would either need a `WizardState` instance, which you can query, or you can implicitly compute it by assigning each event emitter an index number during creation.
