### ISSUE TITLE
Global configurations with forRoot(_options)

### ISSUE THREAD

**Issue by furqanaziz** [madoar/angular-archwizard#77]
I want to change the defaults for my project to fit the need and currently, I have to do everywhere in the project to keep all wizard symmetric. I think there should be an option in forRoot where the user can overwrite all defaults for wizard and wizard-steps globally.

**Comment by madoar** [comment]
About what kind of *defaults* are we speaking? The behavior of the wizard, the css stylesheets, or something else?
For the css stylesheets it's planned to make them changeable by supplying custom css tags inside the application using `ng2-archwizard`, see #46 and #27. 
The problem here is that I'm currently low on time and would appreciate some help.

**Comment by madoar** [comment]
I've just released version `3.0.0` of the library.
Version `3.0.0` is released under a new package name, named [angular-archwizard](https://www.npmjs.com/package/angular-archwizard).

Version `3.0.0` provides you the ability to add custom css to the wizard.
