### ISSUE TITLE
Support for IE < 11

### ISSUE THREAD

**Issue by that0th3rGuy** [madoar/angular-archwizard#94]
I'm using a wizard as part of an Angular application. When viewing the app in IE10 (compatibility mode), the steps are not toggled as expected. Rather, they're all displayed in order at once; please see the image below.

![image](https://user-images.githubusercontent.com/6961636/35275803-916f878a-0049-11e8-80c6-ca369819054e.png)

The buttons work, shifting the navigation pane around as expected, but the displayed step doesn't change.

IE polyfills are loaded as explained in other guides, no exceptions are being thrown in the console. Not sure what else to try, except switching libraries or forking.

**Comment by madoar** [comment]
The reason for this is, that IE 9 and 10 don't seem to know the `hidden` property, which `ng2-archwizard` uses to hide the steps that shouldn't be shown.
Sadly I can't use `*ngIf` instead, because this would remove the steps from the navigation bar at the top too.

If you know of another way to make elements invisible, which works on multiple (all) browsers, feel free to either provide a new PR or give us a suggestion how this could be done.

**Comment by that0th3rGuy** [comment]
Thanks for the feedback!

This "hidden" property you're talking about. Is it an attribute on an element, or a CSS property, or something else?

**Comment by madoar** [comment]
As far as I know `hidden` is a html 5 attribute (see also [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden)).

**Comment by AbdelrhmanSafwat789** [comment]
I am using your module and found a fix to it. you could replace the 'hidden' to 'class.hidden' and then introduce a hidden class in your wizard step component css file with ` display: none !important;`

**Comment by madoar** [comment]
I'm closing this issue for the same reason as #120. If there is still a need to use `angular-archwizard` with a version of Internet Explorer feel free to open a new issue/PR.
